seed: 172

csdp: ~
sdp: ~

model:
  weight_decay: 1e-4
  lr: 3e-4
  lr_backbone: 1e-4
  lr_scheduler: step
  lr_step_size: 2
  lr_gamma: 0.99

  compile: false

  optimizer: muon
  muon_lr: 1e-3
  muon_weight_decay: 3e-3

  input_size_hw: ${data.input_size_hw}
  num_classes: ${data.num_classes}

data:
  dataset: litdetect.data.litdetect.LitDetectDataset

  input_size_hw: [ 512, 512 ]

  train_batch_size: 24
  val_batch_size: 24
  num_workers: 24

  augmentation_train:
    _target_: albumentations.Compose

    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size_hw: ${data.input_size_hw}     # 对应 input_size_hw
        area_for_downscale: image
        p: 1.0

      - _target_: albumentations.PadIfNeeded
        min_height: ${data.input_size_hw.0}
        min_width: ${data.input_size_hw.1}
        border_mode: 0     # cv2.BORDER_CONSTANT = 0
        fill: 0
        p: 1.0

      - _target_: albumentations.SquareSymmetry
        p: 0.5

      - _target_: albumentations.Affine
        scale: [ 0.8, 1.2 ]
        rotate: [ -30, 30 ]
        balanced_scale: true
        p: 0.3

      - _target_: albumentations.Sequential
        transforms:
          - _target_: albumentations.SmallestMaxSize
            max_size: 640
            p: 1.0

          - _target_: albumentations.RandomCrop
            height: ${data.input_size_hw.0}
            width: ${data.input_size_hw.1}
            p: 1.0
        p: 0.1

      - _target_: albumentations.Normalize
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

      - _target_: albumentations.ToTensorV2

    bbox_params:
      _target_: albumentations.BboxParams
      format: pascal_voc
      label_fields: [ labels ]
      min_visibility: 0.5

  augmentation_val:
    _target_: albumentations.Compose

    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size_hw: ${data.input_size_hw}     # 对应 input_size_hw
        area_for_downscale: image
        p: 1.0

      - _target_: albumentations.PadIfNeeded
        min_height: ${data.input_size_hw.0}
        min_width: ${data.input_size_hw.1}
        border_mode: 0     # cv2.BORDER_CONSTANT = 0
        fill: 0
        p: 1.0

      - _target_: albumentations.Normalize
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

      - _target_: albumentations.ToTensorV2

    bbox_params:
      _target_: albumentations.BboxParams
      format: pascal_voc
      label_fields: [ labels ]

callbacks:
  call_back_monitor: map_50
  call_back_mode: max
  early_stop: true
  class_name: ${data.class_name}
  model_name: ${model.model_name}

trainer:
  num_sanity_val_steps: -1
  max_epochs: 200
  #benchmark: true
  check_val_every_n_epoch: 1  # 每训练几轮验证一次
  precision: 16-mixed  # 32-true or 16-mixed 训练精度，16-mixed可以提速，如果loss出nan了就改32-true
  log_every_n_steps: 50
  #profiler: simple
  #sync_batchnorm: true
  #limit_train_batches: 20
  #limit_test_batches: 0.0
  enable_progress_bar: true  # 开关进度条
  enable_model_summary: true
  gradient_clip_val: 0.5
  #detect_anomaly: true
  #accumulate_grad_batches: 2