model_name: detr_module
config_path: /data/16t/wxh/detrex/projects/dino/configs/dino-swin/dino_swin_base_384_4scale_12ep.py
# pretrained_weights: /data/16t/wxh/ds/ckpts/dino_swin_base_384_4scale_12ep.pth
conf_thres: 0.05

dataset: detr

optimizer: adam
lr: 1e-4
lr_backbone: 6e-5
weight_decay: 1e-5
lr_step_size: 1
lr_gamma: 0.975

train_batch_size: 16
val_batch_size: 16
num_workers: 24

sdp: /data/16t/wxh/LitDetect/lightning_logs/version_136/ckpts/detr_module-epoch=064-map_50=0.76545.ckpt