model_name: detr_module
config_path: /data/16t/wxh/detrex/projects/dino/configs/dino-convnext/dino_convnext_small_384_4scale_12ep.py
pretrained_weights: /data/16t/wxh/ds/ckpts/dino_convnext_small_384_4scale_12ep.pth
#config_path: /data/16t/wxh/detrex/projects/dino/configs/dino-swin/dino_swin_base_384_4scale_12ep.py
#pretrained_weights: /data/16t/wxh/ds/ckpts/dino_swin_base_384_4scale_12ep.pth
conf_thres: 0.05

dataset: detr

optimizer: adam
lr: 1e-4
lr_backbone: 1e-4
weight_decay: 1e-4
lr_step_size: 1
lr_gamma: 0.975

train_batch_size: 24
val_batch_size: 32
num_workers: 24
