num_sanity_val_steps: -1
max_epochs: 100
accelerator: gpu
devices: 1  # 多卡训练时设置显卡数量
benchmark: true
check_val_every_n_epoch: 1  # 每训练几轮验证一次
precision: 32-true  # 32-true or 16-mixed 训练精度，16-mixed可以提速，如果loss出nan了就改32-true
log_every_n_steps: 10
limit_train_batches: 60
#limit_test_batches: 0.0
enable_progress_bar: true  # 开关进度条
enable_model_summary: true
gradient_clip_val: 0.5